#include "Log.h"

struct LogChannel logChannels[] = {
   [lc_alpha] = { lc_alpha, "ALPH", -180, 180, true },
   [lc_dynpressure] = { lc_dynpressure, "PRES", -100, 10000 },
   [lc_accx] = { lc_accx, "ACCX", -150, 150 },
   [lc_accy] = { lc_accy, "ACCY", -150, 150 },
   [lc_accz] = { lc_accz, "ACCZ", -150, 150 },
   [lc_roll] = { lc_roll, "ROLL", -180, 180 },
   [lc_rollrate] = { lc_rollrate, "RRTE", -1440, 1440 },
   [lc_pitch] = { lc_pitch, "PTCH", -90, 90 },
   [lc_pitchrate] = { lc_pitchrate, "PRTE", -720, 720 },
   [lc_heading] = { lc_heading, "HEAD", 0, 360},
   [lc_yawrate] = { lc_yawrate, "YRTE", -720, 720},
   [lc_ailestick] = { lc_ailestick, "ASTK", -1, 1 },
   [lc_elevstick] = { lc_elevstick, "ESTK", -1, 1 },
   [lc_thrstick] = { lc_thrstick, "THRO", 0, 1 },
   [lc_rudstick] = { lc_rudstick, "RSTK", -1, 1 },
   [lc_aileron] = { lc_aileron, "AILE", -1.5, 1.5 },
   [lc_aileron_ff] = { lc_aileron_ff, "AIFF", -1.5, 1.5 },
   [lc_elevator] = { lc_elevator, "ELEV", -1.5, 1.5 },
   [lc_elevator_ff] = { lc_elevator_ff, "ELFF", -1.5, 1.5 },
   [lc_rudder] = { lc_rudder, "RUDR", -1.5, 1.5 },
   [lc_mode] = { lc_mode, "MODE", 0, 1 },
   [lc_status] = { lc_status, "STAT", 0, 1 },
   [lc_target] = { lc_target, "TARG", -180, 180 },
   [lc_target_pr] = { lc_target_pr, "TPRT", -180, 180 },
   [lc_trim] = { lc_trim, "TRIM", -180, 180 },
   [lc_gain] = { lc_gain, "GAIN", 0, 50},
   [lc_test] = { lc_test, "TEST", 0, BYTE_MASK },
   [lc_alt] = { lc_alt, "ALTI", -10, 300 } };

